
FROM oven/bun:latest

WORKDIR /app

COPY package*.json ./

RUN bun install && bun add vite -g

COPY . .

RUN bun run build && bun add serve -g

EXPOSE 5173

CMD ["serve", "dist", "-l", "5173"]
