services:
- type: web
  name: moodineko-api
  env: node
  region: frankfurt # sau o altă regiune: oregon, singapore etc.
  plan: free
  buildCommand: cd server && bun install
  startCommand: cd server && bun run index.ts # sau main.ts dacă folosești alt fișier
  envVars:
  - key: PORT
    value: 3000 # Render setează automat portul, dar îl poți folosi din process.env.PORT
  - key: REDIS_URL
    fromService:
      type: redis
      name: MoodiNekoRedis
